// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnjhvmwznqsunjpabacg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuamh2bXd6bnFzdW5qcGFiYWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTQ0MjksImV4cCI6MjA2OTM5MDQyOX0.dLdc08Hq6IpvjSb8cmVNwaTz8s2h439aMviVvNIxYNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});